name: main

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js to 16.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x

      - name: Move config file
        run: |
          cp src/config.example.ts src/config.ts

      - name: Install dependencies
        run: |
          npm install --global yarn
          yarn install
          yarn global add typescript
          yarn global add eslint
          yarn global add jest

      - name: Check TypeScript syntax
        run: |
          npm run check:tsc

      - name: Check code style
        run: |
          npm run check:style

      - name: Run Jest tests
        run: |
          npm run test
